### ISSUE TITLE
Does the latest release work with IPv6?

### ISSUE THREAD

**Issue by pritambarhate** [Anakros/webrtc-ios-dynamic#7]
Hi,

I downloaded (on 26th Sept.) the latest release from here:

https://github.com/Anakros/WebRTC-iOS/releases/tag/13869.6.0

To update an old app which uses WebRTC lib from 2014. Main reason to support IPv6 only networks as required by apple. 

But there are a lot of changes since 2014. I somehow got the video to work with this latest library. But it still doesn't seem to work on IPv6 only network. 

Can anybody please confirm that this release works with IPv6 or not? 

Thanks,

Pritam.

**Comment by AlexKMDev** [comment]
Hi. I don't have any IPv6 networks in availability, so I don't know. You probably should ask in [WebRTC discussion group](https://groups.google.com/forum/#!forum/discuss-webrtc), because there are more people involved.

**Comment by pritambarhate** [comment]
Hi, 

Thanks for the reply.

With Mc OS 10.11 Apple has given a way to create IPv6 only WiFi:

Here is a tutorial on how to set it up: http://www.brianjcoleman.com/tutorial-how-to-test-your-app-for-ipv6-compatibility/

Here is the original issue on Chromium bug tracker which prompted me to find the latest build of WebRTC: 

https://bugs.chromium.org/p/webrtc/issues/detail?id=5871

Near the end it is mentioned that the IPv6 related issue fix should be in M53 release. From the release page linked above it seems that the latest release made here is from the M54 release. So I assumed that the IPv6 fix should be in there. 

Anyways, I will also ask WebRTC discussion group. 

Thanks,

Pritam.

**Comment by NiKrause** [comment]
I guess this issue is fixed. It was a problem in the old libjingle since the latest was a version from January this year. This is all new here. Thanks to the @Anakros. I had problems with it too. But now it seems to work as it should.

**Comment by pritambarhate** [comment]
Yes, the M54 build works with IPv6. I asked on the official issue tracker and dev team confirmed. 

https://bugs.chromium.org/p/webrtc/issues/detail?id=5871

Also I extracted out AppRTCDemo from the main WebRTC codebase and built it with this one. It works on IPv6 only network.

**Comment by AlexKMDev** [comment]
Thanks for the info. This is great that it works with IPv6.

**Comment by gunjot-mansa** [comment]
Hi @pritambarhate and @Anakros 

I am not able to make it work with ipv6. It works perfectly fine with ipv4, but as soon i switch my network to ipv6 - it just shows black screen in place of remote video.

I am using latest pre-release r14604. I have also tried latest release i.e r13869: M54, Update 6, still no luck!

Can you please confirm?
